### ISSUE TITLE
Transmission support?

### ISSUE THREAD

**Issue by tapatianbeast** [bleusakura/magnetfinder#3]
:)

**Comment by bleusakura** [comment]
I'm sure you didn't intend for this, but I have never received a comment on one of my public repositories before, so I feel obliged to accomplish it. Will work on it soon (probably today or tmrw)

**Comment by bleusakura** [comment]
assuming you are using transmission-daemon & transmission-remote (and they are working correctly alone), this has been added! ac1e37650e4f08e363150f3c3a421263321af6b1 

let me know if you have any questions or think there could be other features added!

**Comment by tapatianbeast** [comment]
Wow terrific work! I just have a little doubt: the tool adds the torrent correctly to transmission but does not download it .. let me know if it is a configuration error of mine

**Comment by bleusakura** [comment]
This appears to be an "issue" with transmission itself, make sure in your `/etc/transmission-daemon/settings.json` ( be sure to be using sudo while viewing/editing this ) that `start-added-torrents` is marked as true. If it is then there is probably a different permissions issue with the daemon.

A different, less nice, solution is to manually start the torrent after it get's added by first listing the torrents and finding the added torrent's id `transmission-remote -l`, then starting it using `transmission-remote -t # -s`. 

I don't plan on manually starting torrents through transmission using my script since there's no easy way to know what the next torrent id will be before adding it, and I don't want to just start all of the torrents since there could be one's unrelated to my script.

Any other information will probably be found here: https://linux.die.net/man/1/transmission-remote
