### ISSUE TITLE
Feature request: Allow other download options

### ISSUE THREAD

**Issue by alphastrata** [bleusakura/magnetfinder#5]
It would be great to download magnets for download at a later time, particularly for those using unsupported clients - like transmission etc. I will try to take a crack at this...

**Comment by bleusakura** [comment]
Hey! I just pushed a commit to add support for transmission because you reminded me I've been meaning to add support for it.

In regards to your feature, im not quite sure what you mean by "download magnets", currently if you don't want to auto download you can turn it off and then only receive the magnet links after you select a torrent. Accordingly you can save those links for later or immediately put them into the client of your choosing. 

Do you mean somehow saving the links into a file, or even the torrent file itself? Let me know!
